#############################################################################
# Makefile for building: Tasker
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  Tasker/Tasker.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Tasker/Tasker.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D__TASKER_DEBUG__ -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/fast-alchemist/Tasker"'
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -std=c++14 -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -ITasker -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Tasker1.0.0
DISTDIR = /home/fast-alchemist/Tasker/.tmp/Tasker1.0.0
LINK          = g++
LFLAGS        = -no-pie -Wl,-rpath,@loader_path/../,-rpath,@executable_path/../,-rpath,@executable_path/../Frameworks -Wl,-rpath,@loader_path/,-rpath,@loader_path/ -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Multimedia -lQt5Charts -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Test -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Tasker/AudioDevice.cpp \
		Tasker/AudioHook.cpp \
		Tasker/AudioMachine.cpp \
		Tasker/CommStatsQWidget.cpp \
		Tasker/Commitment.cpp \
		Tasker/CommitmentSnaphot.cpp \
		Tasker/CreateCommitmentQWidget.cpp \
		Tasker/Hook.cpp \
		Tasker/NewSessionQWidget.cpp \
		Tasker/Session.cpp \
		Tasker/Task.cpp \
		Tasker/StatsUtility.cpp \
		Tasker/TaskerPerf/perftimer.cpp \
		Tasker/TaskerUIMainWindowQWidget.cpp \
		Tasker/Timer.cpp \
		Tasker/UdataUtils.cpp \
		Tasker/User.cpp \
		Tasker/XHook.cpp \
		Tasker/livesession.cpp \
		Tasker/mainui.cpp \
		Tasker/main.cpp moc_AudioDevice.cpp \
		moc_AudioHook.cpp \
		moc_AudioMachine.cpp \
		moc_CommStatsQWidget.cpp \
		moc_CreateCommitmentQWidget.cpp \
		moc_Hook.cpp \
		moc_NewSessionQWidget.cpp \
		moc_TaskerUIMainWindowQWidget.cpp \
		moc_Timer.cpp \
		moc_XHook.cpp \
		moc_livesession.cpp \
		moc_mainui.cpp
OBJECTS       = AudioDevice.o \
		AudioHook.o \
		AudioMachine.o \
		CommStatsQWidget.o \
		Commitment.o \
		CommitmentSnaphot.o \
		CreateCommitmentQWidget.o \
		Hook.o \
		NewSessionQWidget.o \
		Session.o \
		Task.o \
		StatsUtility.o \
		perftimer.o \
		TaskerUIMainWindowQWidget.o \
		Timer.o \
		UdataUtils.o \
		User.o \
		XHook.o \
		livesession.o \
		mainui.o \
		main.o \
		moc_AudioDevice.o \
		moc_AudioHook.o \
		moc_AudioMachine.o \
		moc_CommStatsQWidget.o \
		moc_CreateCommitmentQWidget.o \
		moc_Hook.o \
		moc_NewSessionQWidget.o \
		moc_TaskerUIMainWindowQWidget.o \
		moc_Timer.o \
		moc_XHook.o \
		moc_livesession.o \
		moc_mainui.o
DIST          = Tasker/TaskerPerf/README.md \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		Tasker/.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testlib_defines.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Tasker/Tasker/Tasker.pro Tasker/AudioDevice.h \
		Tasker/AudioHook.h \
		Tasker/AudioMachine.h \
		Tasker/CommStatsQWidget.h \
		Tasker/Commitment.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/Hook.h \
		Tasker/NewSessionQWidget.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/Timer.h \
		Tasker/StatsUtility.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/UdataUtils.h \
		Tasker/XHook.h \
		Tasker/livesession.h \
		Tasker/mainui.h \
		Tasker/User.h Tasker/AudioDevice.cpp \
		Tasker/AudioHook.cpp \
		Tasker/AudioMachine.cpp \
		Tasker/CommStatsQWidget.cpp \
		Tasker/Commitment.cpp \
		Tasker/CommitmentSnaphot.cpp \
		Tasker/CreateCommitmentQWidget.cpp \
		Tasker/Hook.cpp \
		Tasker/NewSessionQWidget.cpp \
		Tasker/Session.cpp \
		Tasker/Task.cpp \
		Tasker/StatsUtility.cpp \
		Tasker/TaskerPerf/perftimer.cpp \
		Tasker/TaskerUIMainWindowQWidget.cpp \
		Tasker/Timer.cpp \
		Tasker/UdataUtils.cpp \
		Tasker/User.cpp \
		Tasker/XHook.cpp \
		Tasker/livesession.cpp \
		Tasker/mainui.cpp \
		Tasker/main.cpp
QMAKE_TARGET  = Tasker
DESTDIR       = 
TARGET        = Tasker


first: all
####### Build rules

$(TARGET): ui_CommStatsQWidget.h ui_CreateCommitmentQWidget.h ui_NewSessionQWidget.h ui_TaskerUIMainWindowQWidget.h ui_livesession.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Tasker/Tasker.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testlib_defines.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Tasker/Tasker.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Charts.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Test.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Tasker/Tasker.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testlib_defines.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Tasker/Tasker.pro:
/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt5Charts.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Test.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Tasker/Tasker.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Tasker/AudioDevice.h Tasker/AudioHook.h Tasker/AudioMachine.h Tasker/CommStatsQWidget.h Tasker/Commitment.h Tasker/CommitmentSnapshot.h Tasker/CreateCommitmentQWidget.h Tasker/Hook.h Tasker/NewSessionQWidget.h Tasker/Session.h Tasker/Task.h Tasker/TaskerPerf/perftimer.h Tasker/TaskerUIMainWindowQWidget.h Tasker/Timer.h Tasker/StatsUtility.h Tasker/TaskerUIMainWindowQWidget.h Tasker/UdataUtils.h Tasker/XHook.h Tasker/livesession.h Tasker/mainui.h Tasker/User.h $(DISTDIR)/
	$(COPY_FILE) --parents Tasker/AudioDevice.cpp Tasker/AudioHook.cpp Tasker/AudioMachine.cpp Tasker/CommStatsQWidget.cpp Tasker/Commitment.cpp Tasker/CommitmentSnaphot.cpp Tasker/CreateCommitmentQWidget.cpp Tasker/Hook.cpp Tasker/NewSessionQWidget.cpp Tasker/Session.cpp Tasker/Task.cpp Tasker/StatsUtility.cpp Tasker/TaskerPerf/perftimer.cpp Tasker/TaskerUIMainWindowQWidget.cpp Tasker/Timer.cpp Tasker/UdataUtils.cpp Tasker/User.cpp Tasker/XHook.cpp Tasker/livesession.cpp Tasker/mainui.cpp Tasker/main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Tasker/CommStatsQWidget.ui Tasker/CreateCommitmentQWidget.ui Tasker/NewSessionQWidget.ui Tasker/TaskerUIMainWindowQWidget.ui Tasker/livesession.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -std=c++14 -O2 -std=gnu++1y -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_AudioDevice.cpp moc_AudioHook.cpp moc_AudioMachine.cpp moc_CommStatsQWidget.cpp moc_CreateCommitmentQWidget.cpp moc_Hook.cpp moc_NewSessionQWidget.cpp moc_TaskerUIMainWindowQWidget.cpp moc_Timer.cpp moc_TaskerUIMainWindowQWidget.cpp moc_XHook.cpp moc_livesession.cpp moc_mainui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AudioDevice.cpp moc_AudioHook.cpp moc_AudioMachine.cpp moc_CommStatsQWidget.cpp moc_CreateCommitmentQWidget.cpp moc_Hook.cpp moc_NewSessionQWidget.cpp moc_TaskerUIMainWindowQWidget.cpp moc_Timer.cpp moc_TaskerUIMainWindowQWidget.cpp moc_XHook.cpp moc_livesession.cpp moc_mainui.cpp
moc_AudioDevice.cpp: Tasker/AudioDevice.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/AudioDevice.h -o moc_AudioDevice.cpp

moc_AudioHook.cpp: Tasker/Hook.h \
		Tasker/AudioMachine.h \
		Tasker/AudioDevice.h \
		Tasker/AudioHook.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/AudioHook.h -o moc_AudioHook.cpp

moc_AudioMachine.cpp: Tasker/AudioDevice.h \
		Tasker/AudioMachine.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/AudioMachine.h -o moc_AudioMachine.cpp

moc_CommStatsQWidget.cpp: Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/CommStatsQWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/CommStatsQWidget.h -o moc_CommStatsQWidget.cpp

moc_CreateCommitmentQWidget.cpp: Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/CreateCommitmentQWidget.h -o moc_CreateCommitmentQWidget.cpp

moc_Hook.cpp: Tasker/Hook.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/Hook.h -o moc_Hook.cpp

moc_NewSessionQWidget.cpp: Tasker/livesession.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/NewSessionQWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/NewSessionQWidget.h -o moc_NewSessionQWidget.cpp

moc_TaskerUIMainWindowQWidget.cpp: Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/TaskerUIMainWindowQWidget.h -o moc_TaskerUIMainWindowQWidget.cpp

moc_Timer.cpp: Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/XHook.h \
		Tasker/Timer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/Timer.h -o moc_Timer.cpp

moc_TaskerUIMainWindowQWidget.cpp: Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/TaskerUIMainWindowQWidget.h -o moc_TaskerUIMainWindowQWidget.cpp

moc_XHook.cpp: Tasker/Hook.h \
		Tasker/XHook.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/XHook.h -o moc_XHook.cpp

moc_livesession.cpp: Tasker/TaskerPerf/perftimer.h \
		Tasker/livesession.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/livesession.h -o moc_livesession.cpp

moc_mainui.cpp: Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/mainui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/fast-alchemist/Tasker/Tasker -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Tasker/mainui.h -o moc_mainui.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_CommStatsQWidget.h ui_CreateCommitmentQWidget.h ui_NewSessionQWidget.h ui_TaskerUIMainWindowQWidget.h ui_livesession.h
compiler_uic_clean:
	-$(DEL_FILE) ui_CommStatsQWidget.h ui_CreateCommitmentQWidget.h ui_NewSessionQWidget.h ui_TaskerUIMainWindowQWidget.h ui_livesession.h
ui_CommStatsQWidget.h: Tasker/CommStatsQWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Tasker/CommStatsQWidget.ui -o ui_CommStatsQWidget.h

ui_CreateCommitmentQWidget.h: Tasker/CreateCommitmentQWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Tasker/CreateCommitmentQWidget.ui -o ui_CreateCommitmentQWidget.h

ui_NewSessionQWidget.h: Tasker/NewSessionQWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Tasker/NewSessionQWidget.ui -o ui_NewSessionQWidget.h

ui_TaskerUIMainWindowQWidget.h: Tasker/TaskerUIMainWindowQWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Tasker/TaskerUIMainWindowQWidget.ui -o ui_TaskerUIMainWindowQWidget.h

ui_livesession.h: Tasker/livesession.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Tasker/livesession.ui -o ui_livesession.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

AudioDevice.o: Tasker/AudioDevice.cpp Tasker/AudioDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioDevice.o Tasker/AudioDevice.cpp

AudioHook.o: Tasker/AudioHook.cpp Tasker/AudioHook.h \
		Tasker/Hook.h \
		Tasker/AudioMachine.h \
		Tasker/AudioDevice.h \
		Tasker/TaskerPerf/perftimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioHook.o Tasker/AudioHook.cpp

AudioMachine.o: Tasker/AudioMachine.cpp Tasker/AudioMachine.h \
		Tasker/AudioDevice.h \
		Tasker/TaskerPerf/perftimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioMachine.o Tasker/AudioMachine.cpp

CommStatsQWidget.o: Tasker/CommStatsQWidget.cpp Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		ui_CommStatsQWidget.h \
		Tasker/UdataUtils.h \
		Tasker/mainui.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/Timer.h \
		Tasker/XHook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommStatsQWidget.o Tasker/CommStatsQWidget.cpp

Commitment.o: Tasker/Commitment.cpp Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Commitment.o Tasker/Commitment.cpp

CommitmentSnaphot.o: Tasker/CommitmentSnaphot.cpp Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/TaskerPerf/perftimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommitmentSnaphot.o Tasker/CommitmentSnaphot.cpp

CreateCommitmentQWidget.o: Tasker/CreateCommitmentQWidget.cpp Tasker/CreateCommitmentQWidget.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/TaskerPerf/perftimer.h \
		ui_CreateCommitmentQWidget.h \
		Tasker/CommStatsQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/mainui.h \
		Tasker/TaskerUIMainWindowQWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CreateCommitmentQWidget.o Tasker/CreateCommitmentQWidget.cpp

Hook.o: Tasker/Hook.cpp Tasker/Hook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hook.o Tasker/Hook.cpp

NewSessionQWidget.o: Tasker/NewSessionQWidget.cpp Tasker/Hook.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/StatsUtility.h \
		Tasker/Timer.h \
		Tasker/XHook.h \
		Tasker/User.h \
		Tasker/Commitment.h \
		Tasker/mainui.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/CreateCommitmentQWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewSessionQWidget.o Tasker/NewSessionQWidget.cpp

Session.o: Tasker/Session.cpp Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/StatsUtility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Session.o Tasker/Session.cpp

Task.o: Tasker/Task.cpp Tasker/Task.h \
		Tasker/Hook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Task.o Tasker/Task.cpp

StatsUtility.o: Tasker/StatsUtility.cpp Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StatsUtility.o Tasker/StatsUtility.cpp

perftimer.o: Tasker/TaskerPerf/perftimer.cpp Tasker/TaskerPerf/perftimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o perftimer.o Tasker/TaskerPerf/perftimer.cpp

TaskerUIMainWindowQWidget.o: Tasker/TaskerUIMainWindowQWidget.cpp Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		ui_TaskerUIMainWindowQWidget.h \
		Tasker/mainui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TaskerUIMainWindowQWidget.o Tasker/TaskerUIMainWindowQWidget.cpp

Timer.o: Tasker/Timer.cpp Tasker/Timer.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/XHook.h \
		Tasker/StatsUtility.h \
		Tasker/mainui.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/AudioHook.h \
		Tasker/AudioMachine.h \
		Tasker/AudioDevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o Tasker/Timer.cpp

UdataUtils.o: Tasker/UdataUtils.cpp Tasker/UdataUtils.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/User.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UdataUtils.o Tasker/UdataUtils.cpp

User.o: Tasker/User.cpp Tasker/User.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/UdataUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o Tasker/User.cpp

XHook.o: Tasker/XHook.cpp Tasker/XHook.h \
		Tasker/Hook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XHook.o Tasker/XHook.cpp

livesession.o: Tasker/livesession.cpp Tasker/livesession.h \
		Tasker/TaskerPerf/perftimer.h \
		ui_livesession.h \
		Tasker/Timer.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/XHook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o livesession.o Tasker/livesession.cpp

mainui.o: Tasker/mainui.cpp Tasker/mainui.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/Hook.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/UdataUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainui.o Tasker/mainui.cpp

main.o: Tasker/main.cpp Tasker/AudioHook.h \
		Tasker/Hook.h \
		Tasker/AudioMachine.h \
		Tasker/AudioDevice.h \
		Tasker/CommStatsQWidget.h \
		Tasker/CommitmentSnapshot.h \
		Tasker/Commitment.h \
		Tasker/StatsUtility.h \
		Tasker/Session.h \
		Tasker/Task.h \
		Tasker/TaskerPerf/perftimer.h \
		Tasker/CreateCommitmentQWidget.h \
		Tasker/NewSessionQWidget.h \
		Tasker/livesession.h \
		Tasker/User.h \
		Tasker/TaskerUIMainWindowQWidget.h \
		Tasker/Timer.h \
		Tasker/XHook.h \
		Tasker/UdataUtils.h \
		Tasker/mainui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Tasker/main.cpp

moc_AudioDevice.o: moc_AudioDevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioDevice.o moc_AudioDevice.cpp

moc_AudioHook.o: moc_AudioHook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioHook.o moc_AudioHook.cpp

moc_AudioMachine.o: moc_AudioMachine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioMachine.o moc_AudioMachine.cpp

moc_CommStatsQWidget.o: moc_CommStatsQWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CommStatsQWidget.o moc_CommStatsQWidget.cpp

moc_CreateCommitmentQWidget.o: moc_CreateCommitmentQWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CreateCommitmentQWidget.o moc_CreateCommitmentQWidget.cpp

moc_Hook.o: moc_Hook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Hook.o moc_Hook.cpp

moc_NewSessionQWidget.o: moc_NewSessionQWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewSessionQWidget.o moc_NewSessionQWidget.cpp

moc_TaskerUIMainWindowQWidget.o: moc_TaskerUIMainWindowQWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TaskerUIMainWindowQWidget.o moc_TaskerUIMainWindowQWidget.cpp

moc_Timer.o: moc_Timer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Timer.o moc_Timer.cpp

moc_XHook.o: moc_XHook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_XHook.o moc_XHook.cpp

moc_livesession.o: moc_livesession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_livesession.o moc_livesession.cpp

moc_mainui.o: moc_mainui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainui.o moc_mainui.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Tasker/bin || mkdir -p $(INSTALL_ROOT)/opt/Tasker/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Tasker/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Tasker/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Tasker/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Tasker/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

