FROM ubuntu:18.04

RUN apt-get update && apt-get install -y qt5-default libqt5charts5-dev libx11-dev \
                                                   libxtst-dev \
                                                   libxt-dev \
                                                   libxinerama-dev \
                                                   libx11-xcb-dev \
                                                   libxkbcommon-dev \
                                                   libxkbcommon-x11-dev \
                                                   libxkbfile-dev \
